# Generated by Django 3.1.3 on 2020-11-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='new',
        ),
    ]
